### PR TITLE
fix plotting on matplotlib 1.5

### PR DESCRIPTION
**Pull request by daschw**

### CODE REVIEW

**Comment by isentropic** [comment]
I assume this is related to some deprecation in matplotlib right?

**Comment by daschw** [comment]
Yes, I am waiting for @mortenpi to check if this works on matplotlib 1.5.

**Comment by mortenpi** [comment]
Sorry for not reporting back earlier. Unfortunately, it seems it doesn't work though:

```
julia> plot(xs, ys)
Error showing value of type Plots.Plot{Plots.PyPlotBackend}:
ERROR: PyError ($(Expr(:escape, :(ccall(#= /root/.julia/packages/PyCall/zqDXB/src/pyfncall.jl:43 =# @pysym(:PyObject_Call), PyPtr, (PyPtr, PyPtr, PyPtr), o, pyargsptr, kw))))) <class 'TypeError'>
TypeError("__init__() got an unexpected keyword argument 'facecolor'",)
  File "/usr/lib/python3/dist-packages/matplotlib/axes/_axes.py", line 538, in legend
    self.legend_ = mlegend.Legend(self, handles, labels, **kwargs)

Stacktrace:
 [1] pyerr_check at /root/.julia/packages/PyCall/zqDXB/src/exception.jl:60 [inlined]
 [2] pyerr_check at /root/.julia/packages/PyCall/zqDXB/src/exception.jl:64 [inlined]
 [3] _handle_error(::String) at /root/.julia/packages/PyCall/zqDXB/src/exception.jl:81
 [4] macro expansion at /root/.julia/packages/PyCall/zqDXB/src/exception.jl:95 [inlined]
 [5] #110 at /root/.julia/packages/PyCall/zqDXB/src/pyfncall.jl:43 [inlined]
 [6] disable_sigint at ./c.jl:446 [inlined]
 [7] __pycall! at /root/.julia/packages/PyCall/zqDXB/src/pyfncall.jl:42 [inlined]
 [8] _pycall!(::PyCall.PyObject, ::PyCall.PyObject, ::Tuple{Array{Any,1},Array{Any,1}}, ::Int64, ::PyCall.PyObject) at /root/.julia/packages/PyCall/zqDXB/src/pyfncall.jl:29
 [9] _pycall!(::PyCall.PyObject, ::PyCall.PyObject, ::Tuple{Array{Any,1},Array{Any,1}}, ::Base.Iterators.Pairs{Symbol,Any,NTuple{9,Symbol},NamedTuple{(:loc, :bbox_to_anchor, :scatterpoints, :fontsize, :facecolor, :edgecolor, :framealpha, :fancybox, :borderpad),Tuple{String,NTuple{4,Float64},Int64,Int64,NTuple{4,Float64},NTuple{4,FixedPointNumbers.Normed{UInt8,8}},Float64,Bool,Float64}}}) at /root/.julia/packages/PyCall/zqDXB/src/pyfncall.jl:11
 [10] #_#117 at /root/.julia/packages/PyCall/zqDXB/src/pyfncall.jl:86 [inlined]
 [11] py_add_legend(::Plots.Plot{Plots.PyPlotBackend}, ::Plots.Subplot{Plots.PyPlotBackend}, ::PyCall.PyObject) at /root/.julia/packages/Plots/qAcB4/src/backends/pyplot.jl:1391
 [12] _before_layout_calcs(::Plots.Plot{Plots.PyPlotBackend}) at /root/.julia/packages/Plots/qAcB4/src/backends/pyplot.jl:1227
 [13] prepare_output(::Plots.Plot{Plots.PyPlotBackend}) at /root/.julia/packages/Plots/qAcB4/src/plot.jl:177
 [14] display(::Plots.PlotsDisplay, ::Plots.Plot{Plots.PyPlotBackend}) at /root/.julia/packages/Plots/qAcB4/src/output.jl:149
 [15] display(::Any) at ./multimedia.jl:323
 [16] #invokelatest#1 at ./essentials.jl:712 [inlined]
 [17] invokelatest at ./essentials.jl:711 [inlined]
 [18] print_response(::IO, ::Any, ::Bool, ::Bool, ::Any) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.4/REPL/src/REPL.jl:161
 [19] print_response(::REPL.AbstractREPL, ::Any, ::Bool, ::Bool) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.4/REPL/src/REPL.jl:146
 [20] (::REPL.var"#do_respond#38"{Bool,REPL.var"#48#57"{REPL.LineEditREPL,REPL.REPLHistoryProvider},REPL.LineEditREPL,REPL.LineEdit.Prompt})(::Any, ::Any, ::Any) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.4/REPL/src/REPL.jl:729
 [21] #invokelatest#1 at ./essentials.jl:712 [inlined]
 [22] invokelatest at ./essentials.jl:711 [inlined]
 [23] run_interface(::REPL.Terminals.TextTerminal, ::REPL.LineEdit.ModalInterface, ::REPL.LineEdit.MIState) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.4/REPL/src/LineEdit.jl:2354
 [24] run_frontend(::REPL.LineEditREPL, ::REPL.REPLBackendRef) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.4/REPL/src/REPL.jl:1055
 [25] run_repl(::REPL.AbstractREPL, ::Any) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.4/REPL/src/REPL.jl:206
 [26] (::Base.var"#764#766"{Bool,Bool,Bool,Bool})(::Module) at ./client.jl:383
 [27] #invokelatest#1 at ./essentials.jl:712 [inlined]
 [28] invokelatest at ./essentials.jl:711 [inlined]
 [29] run_main_repl(::Bool, ::Bool, ::Bool, ::Bool, ::Bool) at ./client.jl:367
 [30] exec_options(::Base.JLOptions) at ./client.jl:305
 [31] _start() at ./client.jl:484
```

Happy to test out any suggestions/guesses. I've set up a [Docker image with Ubuntu 16.04 and Julia](https://hub.docker.com/r/mortenpi/julia-ubuntu-1604/tags), so I can easily reproduce this now.
